// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/segmentio/kafka-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// Read provides a mock function for the type MockConsumer
func (_mock *MockConsumer) Read(ctx context.Context, handle func(ctx context.Context, msg kafka.Message) error) error {
	ret := _mock.Called(ctx, handle)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context, msg kafka.Message) error) error); ok {
		r0 = returnFunc(ctx, handle)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumer_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockConsumer_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - handle func(ctx context.Context, msg kafka.Message) error
func (_e *MockConsumer_Expecter) Read(ctx interface{}, handle interface{}) *MockConsumer_Read_Call {
	return &MockConsumer_Read_Call{Call: _e.mock.On("Read", ctx, handle)}
}

func (_c *MockConsumer_Read_Call) Run(run func(ctx context.Context, handle func(ctx context.Context, msg kafka.Message) error)) *MockConsumer_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context, msg kafka.Message) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context, msg kafka.Message) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConsumer_Read_Call) Return(err error) *MockConsumer_Read_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumer_Read_Call) RunAndReturn(run func(ctx context.Context, handle func(ctx context.Context, msg kafka.Message) error) error) *MockConsumer_Read_Call {
	_c.Call.Return(run)
	return _c
}
