// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"app/internal/model"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(ctx context.Context, uuid string) (model.Order, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockService_Expecter) Get(ctx interface{}, uuid interface{}) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, uuid)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, uuid string)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(order model.Order, err error) *MockService_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(ctx context.Context, uuid string) (model.Order, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessOrder provides a mock function for the type MockService
func (_mock *MockService) ProcessOrder(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for ProcessOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ProcessOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessOrder'
type MockService_ProcessOrder_Call struct {
	*mock.Call
}

// ProcessOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *MockService_Expecter) ProcessOrder(ctx interface{}, order interface{}) *MockService_ProcessOrder_Call {
	return &MockService_ProcessOrder_Call{Call: _e.mock.On("ProcessOrder", ctx, order)}
}

func (_c *MockService_ProcessOrder_Call) Run(run func(ctx context.Context, order model.Order)) *MockService_ProcessOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ProcessOrder_Call) Return(err error) *MockService_ProcessOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ProcessOrder_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *MockService_ProcessOrder_Call {
	_c.Call.Return(run)
	return _c
}
