// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"app/internal/model"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) GetOrder(ctx context.Context, uuid string) (model.Order, error) {
	ret := _mock.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.Order, error)); ok {
		return returnFunc(ctx, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.Order); ok {
		r0 = returnFunc(ctx, uuid)
	} else {
		r0 = ret.Get(0).(model.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockRepository_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - uuid string
func (_e *MockRepository_Expecter) GetOrder(ctx interface{}, uuid interface{}) *MockRepository_GetOrder_Call {
	return &MockRepository_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, uuid)}
}

func (_c *MockRepository_GetOrder_Call) Run(run func(ctx context.Context, uuid string)) *MockRepository_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetOrder_Call) Return(order model.Order, err error) *MockRepository_GetOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockRepository_GetOrder_Call) RunAndReturn(run func(ctx context.Context, uuid string) (model.Order, error)) *MockRepository_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SetOrder provides a mock function for the type MockRepository
func (_mock *MockRepository) SetOrder(ctx context.Context, order model.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SetOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetOrder'
type MockRepository_SetOrder_Call struct {
	*mock.Call
}

// SetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *MockRepository_Expecter) SetOrder(ctx interface{}, order interface{}) *MockRepository_SetOrder_Call {
	return &MockRepository_SetOrder_Call{Call: _e.mock.On("SetOrder", ctx, order)}
}

func (_c *MockRepository_SetOrder_Call) Run(run func(ctx context.Context, order model.Order)) *MockRepository_SetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Order
		if args[1] != nil {
			arg1 = args[1].(model.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_SetOrder_Call) Return(err error) *MockRepository_SetOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetOrder_Call) RunAndReturn(run func(ctx context.Context, order model.Order) error) *MockRepository_SetOrder_Call {
	_c.Call.Return(run)
	return _c
}
