// Code generated by ogen, DO NOT EDIT.

package v1

// OperationName is the ogen operation name
type OperationName = string

const (
	GetOrderOperation OperationName = "GetOrder"
	IndexOperation    OperationName = "Index"
)
