// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetOrder implements getOrder operation.
//
// Get order by UID.
//
// GET /order/{orderUID}
func (UnimplementedHandler) GetOrder(ctx context.Context, params GetOrderParams) (r GetOrderRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Index implements index operation.
//
// Web UI.
//
// GET /
func (UnimplementedHandler) Index(ctx context.Context) (r IndexOK, _ error) {
	return r, ht.ErrNotImplemented
}
