// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetOrder implements getOrder operation.
	//
	// Get order by UID.
	//
	// GET /order/{orderUID}
	GetOrder(ctx context.Context, params GetOrderParams) (GetOrderRes, error)
	// Index implements index operation.
	//
	// Web UI.
	//
	// GET /
	Index(ctx context.Context) (IndexOK, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
