// Code generated by ogen, DO NOT EDIT.

package v1

import (
	"io"
	"time"
)

// Ref: #/components/schemas/Delivery
type Delivery struct {
	Name    string `json:"name"`
	Phone   string `json:"phone"`
	Zip     string `json:"zip"`
	City    string `json:"city"`
	Address string `json:"address"`
	Region  string `json:"region"`
	Email   string `json:"email"`
}

// GetName returns the value of Name.
func (s *Delivery) GetName() string {
	return s.Name
}

// GetPhone returns the value of Phone.
func (s *Delivery) GetPhone() string {
	return s.Phone
}

// GetZip returns the value of Zip.
func (s *Delivery) GetZip() string {
	return s.Zip
}

// GetCity returns the value of City.
func (s *Delivery) GetCity() string {
	return s.City
}

// GetAddress returns the value of Address.
func (s *Delivery) GetAddress() string {
	return s.Address
}

// GetRegion returns the value of Region.
func (s *Delivery) GetRegion() string {
	return s.Region
}

// GetEmail returns the value of Email.
func (s *Delivery) GetEmail() string {
	return s.Email
}

// SetName sets the value of Name.
func (s *Delivery) SetName(val string) {
	s.Name = val
}

// SetPhone sets the value of Phone.
func (s *Delivery) SetPhone(val string) {
	s.Phone = val
}

// SetZip sets the value of Zip.
func (s *Delivery) SetZip(val string) {
	s.Zip = val
}

// SetCity sets the value of City.
func (s *Delivery) SetCity(val string) {
	s.City = val
}

// SetAddress sets the value of Address.
func (s *Delivery) SetAddress(val string) {
	s.Address = val
}

// SetRegion sets the value of Region.
func (s *Delivery) SetRegion(val string) {
	s.Region = val
}

// SetEmail sets the value of Email.
func (s *Delivery) SetEmail(val string) {
	s.Email = val
}

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

type GetOrderInternalServerError Error

func (*GetOrderInternalServerError) getOrderRes() {}

type GetOrderNotFound Error

func (*GetOrderNotFound) getOrderRes() {}

type IndexOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s IndexOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

// Ref: #/components/schemas/Item
type Item struct {
	ChrtID      int64  `json:"chrt_id"`
	TrackNumber string `json:"track_number"`
	Price       int32  `json:"price"`
	Rid         string `json:"rid"`
	Name        string `json:"name"`
	Sale        int32  `json:"sale"`
	Size        string `json:"size"`
	TotalPrice  int32  `json:"total_price"`
	NmID        int32  `json:"nm_id"`
	Brand       string `json:"brand"`
	Status      int32  `json:"status"`
}

// GetChrtID returns the value of ChrtID.
func (s *Item) GetChrtID() int64 {
	return s.ChrtID
}

// GetTrackNumber returns the value of TrackNumber.
func (s *Item) GetTrackNumber() string {
	return s.TrackNumber
}

// GetPrice returns the value of Price.
func (s *Item) GetPrice() int32 {
	return s.Price
}

// GetRid returns the value of Rid.
func (s *Item) GetRid() string {
	return s.Rid
}

// GetName returns the value of Name.
func (s *Item) GetName() string {
	return s.Name
}

// GetSale returns the value of Sale.
func (s *Item) GetSale() int32 {
	return s.Sale
}

// GetSize returns the value of Size.
func (s *Item) GetSize() string {
	return s.Size
}

// GetTotalPrice returns the value of TotalPrice.
func (s *Item) GetTotalPrice() int32 {
	return s.TotalPrice
}

// GetNmID returns the value of NmID.
func (s *Item) GetNmID() int32 {
	return s.NmID
}

// GetBrand returns the value of Brand.
func (s *Item) GetBrand() string {
	return s.Brand
}

// GetStatus returns the value of Status.
func (s *Item) GetStatus() int32 {
	return s.Status
}

// SetChrtID sets the value of ChrtID.
func (s *Item) SetChrtID(val int64) {
	s.ChrtID = val
}

// SetTrackNumber sets the value of TrackNumber.
func (s *Item) SetTrackNumber(val string) {
	s.TrackNumber = val
}

// SetPrice sets the value of Price.
func (s *Item) SetPrice(val int32) {
	s.Price = val
}

// SetRid sets the value of Rid.
func (s *Item) SetRid(val string) {
	s.Rid = val
}

// SetName sets the value of Name.
func (s *Item) SetName(val string) {
	s.Name = val
}

// SetSale sets the value of Sale.
func (s *Item) SetSale(val int32) {
	s.Sale = val
}

// SetSize sets the value of Size.
func (s *Item) SetSize(val string) {
	s.Size = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *Item) SetTotalPrice(val int32) {
	s.TotalPrice = val
}

// SetNmID sets the value of NmID.
func (s *Item) SetNmID(val int32) {
	s.NmID = val
}

// SetBrand sets the value of Brand.
func (s *Item) SetBrand(val string) {
	s.Brand = val
}

// SetStatus sets the value of Status.
func (s *Item) SetStatus(val int32) {
	s.Status = val
}

// Ref: #/components/schemas/Order
type Order struct {
	OrderUID          string    `json:"order_uid"`
	TrackNumber       string    `json:"track_number"`
	Entry             string    `json:"entry"`
	Locale            string    `json:"locale"`
	InternalSignature string    `json:"internal_signature"`
	CustomerID        string    `json:"customer_id"`
	DeliveryService   string    `json:"delivery_service"`
	ShardKey          string    `json:"shard_key"`
	SmID              int32     `json:"sm_id"`
	DateCreated       time.Time `json:"date_created"`
	OffShard          string    `json:"off_shard"`
	Delivery          Delivery  `json:"delivery"`
	Payment           Payment   `json:"payment"`
	Items             []Item    `json:"items"`
}

// GetOrderUID returns the value of OrderUID.
func (s *Order) GetOrderUID() string {
	return s.OrderUID
}

// GetTrackNumber returns the value of TrackNumber.
func (s *Order) GetTrackNumber() string {
	return s.TrackNumber
}

// GetEntry returns the value of Entry.
func (s *Order) GetEntry() string {
	return s.Entry
}

// GetLocale returns the value of Locale.
func (s *Order) GetLocale() string {
	return s.Locale
}

// GetInternalSignature returns the value of InternalSignature.
func (s *Order) GetInternalSignature() string {
	return s.InternalSignature
}

// GetCustomerID returns the value of CustomerID.
func (s *Order) GetCustomerID() string {
	return s.CustomerID
}

// GetDeliveryService returns the value of DeliveryService.
func (s *Order) GetDeliveryService() string {
	return s.DeliveryService
}

// GetShardKey returns the value of ShardKey.
func (s *Order) GetShardKey() string {
	return s.ShardKey
}

// GetSmID returns the value of SmID.
func (s *Order) GetSmID() int32 {
	return s.SmID
}

// GetDateCreated returns the value of DateCreated.
func (s *Order) GetDateCreated() time.Time {
	return s.DateCreated
}

// GetOffShard returns the value of OffShard.
func (s *Order) GetOffShard() string {
	return s.OffShard
}

// GetDelivery returns the value of Delivery.
func (s *Order) GetDelivery() Delivery {
	return s.Delivery
}

// GetPayment returns the value of Payment.
func (s *Order) GetPayment() Payment {
	return s.Payment
}

// GetItems returns the value of Items.
func (s *Order) GetItems() []Item {
	return s.Items
}

// SetOrderUID sets the value of OrderUID.
func (s *Order) SetOrderUID(val string) {
	s.OrderUID = val
}

// SetTrackNumber sets the value of TrackNumber.
func (s *Order) SetTrackNumber(val string) {
	s.TrackNumber = val
}

// SetEntry sets the value of Entry.
func (s *Order) SetEntry(val string) {
	s.Entry = val
}

// SetLocale sets the value of Locale.
func (s *Order) SetLocale(val string) {
	s.Locale = val
}

// SetInternalSignature sets the value of InternalSignature.
func (s *Order) SetInternalSignature(val string) {
	s.InternalSignature = val
}

// SetCustomerID sets the value of CustomerID.
func (s *Order) SetCustomerID(val string) {
	s.CustomerID = val
}

// SetDeliveryService sets the value of DeliveryService.
func (s *Order) SetDeliveryService(val string) {
	s.DeliveryService = val
}

// SetShardKey sets the value of ShardKey.
func (s *Order) SetShardKey(val string) {
	s.ShardKey = val
}

// SetSmID sets the value of SmID.
func (s *Order) SetSmID(val int32) {
	s.SmID = val
}

// SetDateCreated sets the value of DateCreated.
func (s *Order) SetDateCreated(val time.Time) {
	s.DateCreated = val
}

// SetOffShard sets the value of OffShard.
func (s *Order) SetOffShard(val string) {
	s.OffShard = val
}

// SetDelivery sets the value of Delivery.
func (s *Order) SetDelivery(val Delivery) {
	s.Delivery = val
}

// SetPayment sets the value of Payment.
func (s *Order) SetPayment(val Payment) {
	s.Payment = val
}

// SetItems sets the value of Items.
func (s *Order) SetItems(val []Item) {
	s.Items = val
}

func (*Order) getOrderRes() {}

// Ref: #/components/schemas/Payment
type Payment struct {
	Transaction  string `json:"transaction"`
	Request      string `json:"request"`
	Currency     string `json:"currency"`
	Provider     string `json:"provider"`
	Amount       int32  `json:"amount"`
	PaymentDt    int32  `json:"payment_dt"`
	Bank         string `json:"bank"`
	DeliveryCost int32  `json:"delivery_cost"`
	GoodsTotal   int32  `json:"goods_total"`
	CustomFee    int32  `json:"custom_fee"`
}

// GetTransaction returns the value of Transaction.
func (s *Payment) GetTransaction() string {
	return s.Transaction
}

// GetRequest returns the value of Request.
func (s *Payment) GetRequest() string {
	return s.Request
}

// GetCurrency returns the value of Currency.
func (s *Payment) GetCurrency() string {
	return s.Currency
}

// GetProvider returns the value of Provider.
func (s *Payment) GetProvider() string {
	return s.Provider
}

// GetAmount returns the value of Amount.
func (s *Payment) GetAmount() int32 {
	return s.Amount
}

// GetPaymentDt returns the value of PaymentDt.
func (s *Payment) GetPaymentDt() int32 {
	return s.PaymentDt
}

// GetBank returns the value of Bank.
func (s *Payment) GetBank() string {
	return s.Bank
}

// GetDeliveryCost returns the value of DeliveryCost.
func (s *Payment) GetDeliveryCost() int32 {
	return s.DeliveryCost
}

// GetGoodsTotal returns the value of GoodsTotal.
func (s *Payment) GetGoodsTotal() int32 {
	return s.GoodsTotal
}

// GetCustomFee returns the value of CustomFee.
func (s *Payment) GetCustomFee() int32 {
	return s.CustomFee
}

// SetTransaction sets the value of Transaction.
func (s *Payment) SetTransaction(val string) {
	s.Transaction = val
}

// SetRequest sets the value of Request.
func (s *Payment) SetRequest(val string) {
	s.Request = val
}

// SetCurrency sets the value of Currency.
func (s *Payment) SetCurrency(val string) {
	s.Currency = val
}

// SetProvider sets the value of Provider.
func (s *Payment) SetProvider(val string) {
	s.Provider = val
}

// SetAmount sets the value of Amount.
func (s *Payment) SetAmount(val int32) {
	s.Amount = val
}

// SetPaymentDt sets the value of PaymentDt.
func (s *Payment) SetPaymentDt(val int32) {
	s.PaymentDt = val
}

// SetBank sets the value of Bank.
func (s *Payment) SetBank(val string) {
	s.Bank = val
}

// SetDeliveryCost sets the value of DeliveryCost.
func (s *Payment) SetDeliveryCost(val int32) {
	s.DeliveryCost = val
}

// SetGoodsTotal sets the value of GoodsTotal.
func (s *Payment) SetGoodsTotal(val int32) {
	s.GoodsTotal = val
}

// SetCustomFee sets the value of CustomFee.
func (s *Payment) SetCustomFee(val int32) {
	s.CustomFee = val
}
